NORMALIZED_KEYWORDS = [
    "decrease anticoagulant activities",
    "increase anticoagulant activities",
    "serum concentration decreased",
    "serum concentration increased",
    "therapeutic efficacy decreased",
    "therapeutic efficacy increased",
    "metabolism increased",
    "metabolism decreased",
    "adverse effects increased",
    "decrease cardiotoxic activities",
    "increase cardiotoxic activities",
    "increase qtcprolonging activities",
    "decrease excretion rate",
    "decrease antihypertensive activities",
    "increase neuroexcitatory activities",
    "decrease diuretic activities",
    "increase neutropenic activities",
    "increase immunosuppressive activities",
    "increase nephrotoxic activities",
    "decrease absorption",
    "increase hyperkalemic activities",
    "increase hypotensive activities",
    "increase serotonergic activities",
    "increase sedative activities",
    "increase hypoglycemic activities",
    "increase bradycardic activities",
    "increase central nervous system depressant activities",
    "increase antiplatelet activities",
    "decrease antineoplastic activities",
    "risk hypersensitivity reaction increased",
    "increase myopathic rhabdomyolysis activities",
    "increase hyponatremic activities",
    "increase anticholinergic activities",
    "increase neuromuscular blocking activities",
    "increase thrombogenic activities",
    "increase stimulatory activities",
    "increase hepatotoxic activities",
    "increase photosensitizing activities",
    "increase atrioventricular blocking activities",
    "increase adverse neuromuscular activities",
    "increase vasoconstricting activities",
    "serum concentration metabolites reduced",
    "increase antihypertensive activities",
    "increase absorption",
    "increase neurotoxic activities",
    "increase hypokalemic activities",
    "increase hypocalcemic activities",
    "increase hypertensive activities", 
    "increase constipating activities",
    "decrease the stimulatory activities",
    "bioavailability decreased", 
    "decrease sedative activities", 
    "increase respiratory depressant", 
    "decrease bronchodilatory activities", 
    "increase analgesic activities",
    "increase arrhythmogenic activities",
    "increase fluid retaining activities", 
    "increase tachycardic activities", 
    "decrease analgesic activities", 
    "decrease effectiveness",
    "decrease neuromuscular blocking activities", 
    "decrease effectiveness", 
    "increase vasopressor activities", 
    "increase vasodilatory activities",
    "decrease vasoconstricting activities",
    "increase ulcerogenic activities", 
    "increase hyperglycemic activities", 
    "may increase the excretion rate"
    
]